"""The observatory's feature roadmap, as data.

Kept here rather than only in Markdown so the dashboard can render it live at
the ROADMAP tab — the roadmap is part of the product, not a side document.
`status` is one of: shipped | building | next | later.
"""

PHASES = [
    {
        "title": "PHASE 0 · THE KERNEL",
        "status": "shipped",
        "note": "Hubble's pipeline extracted into a domain-agnostic core. "
                "Adding a telescope now costs a source adapter plus a config "
                "block, not a rewrite.",
        "items": [
            {"name": "telescope/ kernel package", "done": True,
             "detail": "cache, http, ranking, events, snapshots, notifier, registry"},
            {"name": "Declarative signals", "done": True,
             "detail": "each telescope's sliders and score breakdown generate themselves"},
            {"name": "Declarative event rules", "done": True,
             "detail": "NewLeader / NewEntrant / Climber / Delta / Threshold shapes"},
            {"name": "Per-telescope toggles", "done": True,
             "detail": "persisted to data/observatory.json; disabled scopes never fetch or poll"},
            {"name": "Generic dashboard", "done": True,
             "detail": "table, podium and sliders rendered from telescope metadata"},
            {"name": "Merged observatory feed", "done": True,
             "detail": "one newest-first stream across every enabled telescope"},
            {"name": "Per-telescope poll cadence", "done": True,
             "detail": "Hubble 6h, Jackson 24h — slow data isn't swept hourly"},
        ],
    },
    {
        "title": "PHASE 1 · THE FIRST FOUR INSTRUMENTS",
        "status": "shipped",
        "note": "All four run on live public data with no API keys.",
        "items": [
            {"name": "🔭 Hubble · AI", "done": True,
             "detail": "HuggingFace + OpenRouter + Artificial Analysis + arena"},
            {"name": "🛡 Jackson · Defense", "done": True,
             "detail": "USAspending obligations, 12m vs prior 12m, + PSC capability panel"},
            {"name": "💰 Simons · Capital", "done": True,
             "detail": "FRED + Yahoo + CoinGecko, ranked by abnormality not opinion"},
            {"name": "🪐 Kepler · Startups", "done": True,
             "detail": "SEC Form D raise detection + HN attention + stealth flagging"},
            {"name": "Live smoke tests", "done": True,
             "detail": "tests/ hits every real source and asserts on shape, not fixtures"},
        ],
    },
    {
        "title": "PHASE 2 · THE REMAINING INSTRUMENTS",
        "status": "shipped",
        "note": "All six telescopes now run. Holmdel shipped without a research "
                "source: every free scholarly API is unusable from this "
                "deployment, so it reads attention and adoption and says so "
                "rather than faking scholarship.",
        "items": [
            {"name": "📡 Holmdel · Ideas", "done": True,
             "detail": "HN + Wikipedia + npm velocity over a 32-topic curated watchlist"},
            {"name": "🚛 Reddington · Logistics", "done": True,
             "detail": "FRED freight volume/cost + freight-sector equities, index level"},
            {"name": "Shared series kernel", "done": True,
             "detail": "telescope/series.py — Simons and Reddington share adapters and analytics"},
            {"name": "Small-denominator gate", "done": True,
             "detail": "Holmdel reports no growth below 12 stories rather than a loud +500%"},
        ],
    },
    {
        "title": "PHASE 2B · UNBLOCKING HOLMDEL",
        "status": "next",
        "note": "Holmdel's research blindness is an access problem, not a "
                "design one. Each item below restores a source that exists but "
                "is unreachable from this deployment.",
        "items": [
            {"name": "OpenAlex research velocity", "done": True,
             "detail": "no key needed — the prior 429s were the sandboxed deployment's "
                       "shared egress IP, not OpenAlex itself; restores paper_growth "
                       "and paper_recent to Holmdel on the same quoted-phrase, "
                       "two-window pattern as its HN signal"},
            {"name": "arXiv preprint velocity", "done": True,
             "detail": "shipped via the simple REST query API, not OAI-PMH — its "
                       "documented ~1-req/3s etiquette turned out to make the bulk-"
                       "harvest protocol unnecessary. But a second, undocumented "
                       "limit showed up under real sustained load that a short burst "
                       "test didn't reveal: a full 32-topic sweep started drawing "
                       "429s about twenty requests in and stayed throttled for the "
                       "rest of that sweep, clearing again a few minutes later. Topic "
                       "order now rotates by day so the same topics aren't always "
                       "the ones that land before the throttle. Kept as its own "
                       "signal rather than summed with OpenAlex's: OpenAlex already "
                       "indexes arXiv, so combining counts would double-count the "
                       "same papers. This was the highest-value item left standing "
                       "precisely because OpenAlex has been quota-exhausted for "
                       "several sweeps running — arXiv gives Holmdel a working "
                       "research-adjacent signal again right now, and a second "
                       "CrossoverRule (arxiv_growth -> repo_growth) keeps "
                       "crossing_over observable through either scholarly surface "
                       "being down independently of the other. Verifying this also "
                       "caught a real bug in the *first* CrossoverRule, latent since "
                       "it shipped: it never required the lagging signal to be "
                       "newly elevated, so once arxiv_growth supplied a real "
                       "non-None leading value, an unchanged snapshot compared "
                       "against itself started firing every time — fixed in "
                       "telescope/events.py, generic, not Holmdel-specific"},
            {"name": "GitHub repo velocity", "done": True,
             "detail": "new-repo creation velocity + peak stars, 180-day window vs "
                       "prior, on the same quoted-phrase pattern as HN/OpenAlex. The "
                       "real limit turned out stricter than first read: GitHub's "
                       "*search* endpoint caps at 10 req/min unauthenticated, not the "
                       "~60/hour of its other APIs — a full 32-topic sweep now takes "
                       "several minutes, paced accordingly. Matches repo name and "
                       "description only, not READMEs"},
            {"name": "Holmdel crossover event", "done": True,
             "detail": "new kernel rule shape, CrossoverRule in telescope/events.py — "
                       "generic, not Holmdel-specific: fires when a leading field was "
                       "elevated in the PREVIOUS snapshot and a different, lagging "
                       "field is elevated in the CURRENT one. Wired to paper_growth "
                       "(leading) -> repo_growth (lagging) for 'research becomes "
                       "builders'. Deliberately doesn't require the leading signal to "
                       "have cooled — a two-point diff can't honestly tell 'declining' "
                       "from 'still high'. Couldn't observe a real live firing this "
                       "iteration (paper_growth is still None while OpenAlex's quota "
                       "is exhausted), so verified end-to-end against a real Holmdel "
                       "row with realistic values patched in for the still-down signal"},
            {"name": "Holmdel UNLISTED panel", "done": True,
             "detail": "new secondary panel — HN stories with 80+ points in the last "
                       "14 days that match none of the curated watchlist's topic "
                       "queries. TELESCOPES.md's stated path for topics (which have "
                       "no natural join key) is 'curated watchlist that auto-expands "
                       "... graduate to embedding-cluster matching later' — this is "
                       "the auto-expand half, not the embedding-cluster half, which "
                       "stays genuinely future work below since it needs embedding "
                       "infrastructure this deployment doesn't have. Deliberately a "
                       "discovery aid, not a new ranked signal: no attempt to cluster "
                       "the unmatched titles into candidate topics automatically, "
                       "same shape as Jackson's UNMAPPED panel surfacing defense "
                       "startups outside its own board rather than trying to score "
                       "them. Needed base.py's panels() list support, already built "
                       "for Jackson, so Holmdel's existing FIELDS panel and this one "
                       "coexist. Verified against real, current data: correctly "
                       "surfaced 20 genuinely off-watchlist trending stories (a "
                       "DeepSeek model release, an Oracle/OpenJDK AI-code ban, "
                       "Danish high schools requiring verbal defense of written "
                       "work) and correctly excluded anything matching a curated "
                       "topic phrase"},
            {"name": "Topic auto-discovery · embedding-cluster resolution", "done": False,
             "detail": "the harder half of graduating past a fixed watchlist — "
                       "clustering emergent topics by meaning rather than exact "
                       "phrase match. Needs embedding infrastructure (a model or a "
                       "keyed API) this deployment doesn't have; not attempted "
                       "without one"},
            {"name": "Semantic Scholar key", "done": False,
             "detail": "still blocked without one — its unauthenticated quota is a "
                       "small pool shared globally by every unkeyed caller, confirmed "
                       "not a proxy artifact by retrying locally with backoff"},
        ],
    },
    {
        "title": "PHASE 3 · MAKING THE SIGNAL SHARPER",
        "status": "next",
        "note": "Everything here improves telescopes that already exist.",
        "items": [
            {"name": "Kepler entity resolution", "done": True,
             "detail": "a guessed '.com' domain per issuer, verified against the "
                       "homepage's own <title> before being trusted — load-bearing, "
                       "not a formality: verifying this live, a random real filer's "
                       "guessed domain resolved to an unrelated squatted gambling "
                       "site. When a domain resolves, HN attention switches from "
                       "fuzzy title-text search to checking the story's own linked "
                       "URL — a precision/recall trade, not a strict upgrade: it "
                       "catches a company's own launch posts more reliably but "
                       "misses third-party news coverage linking to a news site "
                       "instead. Kepler takes that trade because a false 'no "
                       "attention' costs nothing (renormalises away) while a false "
                       "'attention found' is the exact failure this instrument "
                       "exists to avoid. Only 12/220 issuers resolved a domain this "
                       "sweep — most pre-launch filers simply have no live site yet"},
            {"name": "Kepler hiring signal", "done": True,
             "detail": "open-role counts from Greenhouse/Lever/Ashby, join key is a "
                       "guessed slug from the company name — not a real identifier "
                       "like Form D's CIK. Greenhouse hits are verified against the "
                       "board's own stated company name; Lever/Ashby have no such "
                       "check, so those rest on slug distinctiveness alone. Verified "
                       "live (MedRhythms, Inc. -> Lever, 8 open clinical roles, "
                       "confirmed genuine not a collision) and checked SAM.gov as an "
                       "alternative for the next item down — it 404s without a "
                       "registered API key, same blocked-without-a-key category as "
                       "Semantic Scholar. Also fixed a kernel bug found in the "
                       "process: telescope/http.py retried a plain 404 three times "
                       "with backoff before giving up, wasting ~2.5s per guess on "
                       "an expected-common case"},
            {"name": "Jackson solicitations", "done": False,
             "detail": "SAM.gov opportunities as a leading indicator ahead of "
                       "obligations — confirmed blocked without a registered API "
                       "key (404 on the public search path), same category as "
                       "Semantic Scholar, not attempted further without one"},
            {"name": "Jackson vendor concentration", "done": False,
             "detail": "TELESCOPES.md spec's 'vendor win rate & concentration' "
                       "signal, never built — attempted, then correctly reverted "
                       "before landing. USAspending's spending_by_award endpoint "
                       "returns each award's Amount already sorted descending, "
                       "so the first per-prime occurrence looked like a cheap way "
                       "to get 'largest single contract' and compute concentration "
                       "as a share of trailing-12m obligations. Verified against "
                       "real, current data before trusting the arithmetic, per "
                       "usual practice — and the result was wrong: several primes "
                       "showed concentration over 100% (Boeing 140.8%, Triwest "
                       "162.2%), which is only possible if the two numbers being "
                       "divided aren't measuring the same thing. Direct inspection "
                       "of the raw API response confirmed why: 'Award Amount' is "
                       "the contract's total lifetime value (Lockheed's top result "
                       "spans 2017-2031), not the amount obligated within any "
                       "requested time_period — the filter selects which awards "
                       "show up, it doesn't scope the amount field, so comparing "
                       "it against a real 12-month obligations figure is apples "
                       "to oranges regardless of the ratio's actual value, not "
                       "just when it exceeds 100%. Getting real per-award, "
                       "date-scoped obligated amounts would need the "
                       "transaction-level API, priced across every top prime's "
                       "full award history — a genuinely larger undertaking, not "
                       "a one-line fix. Left unbuilt rather than shipped "
                       "misleading, matching this project's own standard: never "
                       "substitute a proxy and present it as the real thing"},
            {"name": "Jackson tech-area board", "done": True,
             "detail": "the CAPABILITY AREAS panel now has a real blended score "
                       "(scale + momentum, equally weighted, log-scaled scale), not "
                       "just a table sorted by raw obligations — reassessed the "
                       "item rather than carry forward the earlier 'needs a bigger "
                       "multi-board architecture' assumption: telescope.ranking."
                       "score() was never actually tied to Telescope.rank()'s one-"
                       "board-per-class assumption, it just takes rows/signals/"
                       "weights, so a panel can be genuinely scored by calling it "
                       "directly, no kernel change needed. Also generalised panel "
                       "sortability while here — every telescope's every panel can "
                       "now be sorted by clicking any column header, client-side, "
                       "independent per panel — since 'rankable' should mean more "
                       "than one fixed order. Verified against real, current data: "
                       "the new score re-ranks Guided Missiles ($26.4B, +53.2% "
                       "growth) above Aircraft, Fixed Wing ($34.5B, +16.7%), which "
                       "a raw-amount sort never would have; confirmed clicking a "
                       "column header re-sorts correctly and independently per "
                       "panel, and that switching telescopes resets sort state so "
                       "it can't bleed into a differently-shaped panel"},
            {"name": "Jackson · unmapped defense startups", "done": True,
             "detail": "cross-telescope join, not a new source — Jackson's obligations "
                       "board can only see companies that already hold a DoD contract; "
                       "a new panel reads Kepler's already-cached Form D feed (never "
                       "forces it to refresh) and keeps filings whose name or industry "
                       "reads defense/dual-use. Keyword-on-name only, so it misses "
                       "deliberately-named stealth companies (Anduril doesn't say "
                       "'defense' anywhere) and is often empty — obvious-by-name "
                       "defense filers are rare in any 12-day window. Needed a kernel "
                       "change: telescope.panels() so a telescope can return more than "
                       "one secondary board (Jackson now has two)"},
            {"name": "Simons 13F whale tracking", "done": True,
             "detail": "new WHALE MOVES panel — quarter-over-quarter position deltas "
                       "across a curated watchlist of 11 large filers (Berkshire, "
                       "Renaissance, Citadel, and 8 more, CIKs confirmed live against "
                       "EDGAR's company search, not from memory). Real complexity "
                       "assessed with a research pass before committing to it: the "
                       "informationTable XML filename is filer-chosen, not fixed "
                       "like Form D's primary_doc.xml, so each filing needs its own "
                       "index lookup first; a large filer can split one security "
                       "across several manager rows (Berkshire's subsidiary "
                       "'otherManager' breakdown, confirmed live, not hypothetical), "
                       "so positions are summed by CUSIP within a filing before ever "
                       "comparing quarters. 45-day filing lag stated plainly on the "
                       "panel itself. Verified against real, current data: Berkshire "
                       "trimming Apple and American Express while adding Alphabet "
                       "and Occidental, Citadel cutting Tesla/Nvidia while adding "
                       "Micron/SanDisk — all matching real, independently "
                       "corroborated portfolio moves, not just internally consistent "
                       "numbers. Lifted a `money()` formatter into telescope/events.py "
                       "along the way: Jackson, Kepler and now Simons each had an "
                       "identical private copy"},
            {"name": "Backfill history", "done": True,
             "detail": "new Telescope.historical_rows() hook: reconstructs a real "
                       "one-period-ago baseline from data a telescope already fetched "
                       "for its own growth math (a prior-window value, never "
                       "fabricated), so the very first sweep can diff against "
                       "something instead of announcing nothing until a second live "
                       "sweep — a full day away at a 24h poll cadence. Wired into "
                       "Holmdel and Jackson, which already carry the needed prior "
                       "fields; Kepler's Form D filings are discrete point-in-time "
                       "events with nothing to reconstruct, so it correctly gets "
                       "none — the honest default, not a gap to fill. Verified "
                       "against real cached data, not synthetic: simulating "
                       "Holmdel's and Jackson's first-ever sweep produced 28 and 41 "
                       "real events respectively (AI Agents repos +248%, Dynetics "
                       "obligations +127%, both matching numbers already visible on "
                       "the live boards). That verification also surfaced a real, "
                       "unrelated bug — a None field rendered as the literal text "
                       "'None' in a headline — fixed in telescope/events.py"},
            {"name": "Per-signal explanations", "done": True,
             "detail": "hover a score to see raw value, normalised value, weight "
                       "and point contribution per signal, plus why a row was "
                       "dampened if it was — generic across all six telescopes"},
        ],
    },
    {
        "title": "PHASE 4 · THE OBSERVATORY LAYER",
        "status": "later",
        "note": "Where a fleet beats a collection: cross-telescope joins.",
        "items": [
            {"name": "Cross-telescope joins · Jackson SBIR → Kepler candidate",
             "done": False,
             "detail": "still blocked — Jackson's own SBIR fetch has been "
                       "unreliable (429/403) since HANDOFF flagged it, worse than "
                       "'rate-limits hard'; not worth building a join on top of a "
                       "source that unreliable"},
            {"name": "Cross-telescope joins · Holmdel crossover → Kepler sector",
             "done": True,
             "detail": "new SECTOR HEAT panel on Kepler — reads Holmdel's already-"
                       "recorded crossing_over events (never forces a Holmdel "
                       "sweep) and surfaces Kepler issuers whose SEC industry maps "
                       "to that topic's field, via a hand-curated, stated-"
                       "approximate mapping (SEC's finite industry list has no "
                       "'aerospace' or 'security' category at all). Verified "
                       "against real fired events, not synthetic — crossing_over "
                       "had actually fired twice by this iteration (Mechanistic "
                       "Interpretability, World Models, both group=AI), and the "
                       "panel correctly surfaced 15 real Kepler issuers in "
                       "AI-adjacent industries. Caught and fixed a real attribution "
                       "bug during verification: when two topics map to the same "
                       "industry, the panel was crediting only whichever topic "
                       "happened to be inserted first instead of both"},
            {"name": "Saved views / theses", "done": True,
             "detail": "name the current weighting, click it later to reapply — "
                       "persisted client-side (localStorage), scoped per telescope, "
                       "not round-tripped through the server: a slider config is "
                       "meaningless without the browser that set it. Deliberately "
                       "picked as the next item over the two remaining Phase 3 "
                       "options (Jackson tech-area board needs a bigger multi-board "
                       "ranking architecture; Jackson solicitations is blocked on a "
                       "SAM.gov key) after a run of iterations spent on flaky "
                       "external APIs (OpenAlex still down, arXiv throttling, "
                       "GitHub's strict limit, SAM.gov and Semantic Scholar both "
                       "key-gated) — a purely internal feature with zero external "
                       "dependency and full in-browser verifiability. Verified via "
                       "direct DOM/JS inspection end-to-end: save, persist across a "
                       "real page reload, apply (weights update to the exact saved "
                       "values), scope isolation (a view saved on Holmdel does not "
                       "appear on Kepler), delete"},
            {"name": "Watchlists + alerts", "done": True,
             "detail": "star any row (any telescope) to watch it — persisted "
                       "client-side, same reasoning as saved views: no user "
                       "account for a server to attach it to, meaningless without "
                       "the browser that set it. 'Alerts' means surfacing what's "
                       "already in the merged event feed for starred entities, not "
                       "a push mechanism — there's no delivery channel to push "
                       "through when nobody's looking. A WATCHED ONLY filter on "
                       "the board and a separate one on the feed, watched feed "
                       "items get a left-border highlight and a star marker. "
                       "Picked over the two remaining Phase 3 items for the same "
                       "reason saved views was: zero external dependency, full "
                       "in-browser verifiability, after a run of iterations on "
                       "flaky external APIs. Verified end-to-end via direct DOM/JS "
                       "inspection: toggle a star, confirm persistence across a "
                       "real page reload, confirm the board's WATCHED ONLY filter "
                       "shows exactly the starred row, confirm the merged feed "
                       "correctly flags and filters to the one real event "
                       "matching a starred entity, confirm scope isolation (a "
                       "watch on Holmdel doesn't leak into Kepler)"},
            {"name": "Morning brief", "done": True,
             "detail": "new telescope/brief.py composes one digest across every "
                       "enabled telescope (current leader + recent events), reading "
                       "already-cached boards and already-recorded events only — "
                       "never forces a sweep, so it's always cheap regardless of "
                       "how expensive any one telescope's own collect() is. A new "
                       "background scheduler (OBSERVATORY_BRIEF_HOURS, default 24) "
                       "dispatches it through the same Discord/Slack channels "
                       "regular events already use (both genuinely wired — real "
                       "webhook POSTs gated on env vars, not stubs — confirmed by "
                       "reading notifier.py before building on it). No real webhook "
                       "is configured in this environment, so verified two ways "
                       "instead of live delivery: a new BRIEF tab renders the same "
                       "digest in-browser with a SEND NOW button hitting the same "
                       "dispatch path the schedule uses, and calling dispatch_brief() "
                       "directly (bypassing Flask's stdout buffering, which delayed "
                       "the print in the dev server's own log tail) confirmed the "
                       "exact digest text logs correctly. Verified against real, "
                       "current data across all six telescopes at once — including "
                       "Hubble's actual current #1 model and Holmdel's 39 real "
                       "accumulated events, not synthetic data"},
            {"name": "Channels", "done": False,
             "detail": "Discord and Slack are wired; X needs credentials"},
            {"name": "Signal-quality feedback", "done": True,
             "detail": "new kernel rule shape, FlagFlipRule in telescope/events.py — "
                       "generic, not Kepler-specific: fires when a boolean field "
                       "flips between two snapshots. Wired to Kepler's stealth flag "
                       "(True -> False only, the one direction that's possible: an "
                       "HN story appearing is permanent, a filing's economics never "
                       "change) as a GRADUATED event — the exact moment a detection "
                       "made with zero public footprint gets its first public "
                       "confirmation, which is what 'did Kepler beat the intro' is "
                       "actually asking. No real graduation has happened yet in this "
                       "deployment's own history — checked the accumulated snapshot "
                       "history first rather than assume (only 2 real snapshots "
                       "exist so far, zero flips) — so verified against a real "
                       "issuer row with the field patched to simulate the "
                       "transition, the same approach used for crossing_over before "
                       "it had ever fired for real. Confirmed the generic diff-"
                       "roundtrip test doesn't spuriously fire it on unrelated "
                       "changes"},
        ],
    },
    {
        "title": "PHASE 5 · HARDENING",
        "status": "next",
        "note": "Every named feature is either shipped or blocked on something "
                "external (a SAM.gov key, SBIR's own unreliable API, X "
                "credentials) — re-checked both live before starting this phase "
                "rather than carry the assumption forward, still blocked. This "
                "phase is for closing gaps a feature's own commit message "
                "already flagged and deferred, so they don't just sit as "
                "comments forever.",
        "items": [
            {"name": "Holmdel cache resilience — complete the rollout", "done": True,
             "detail": "the is_empty total-failure guard (added to Cache.cached() "
                       "after a real incident zeroed Holmdel's OpenAlex signal for "
                       "half a day) only ever got wired into the three sources built "
                       "after that fix — OpenAlex, arXiv, GitHub. HN, Wikipedia and "
                       "npm were explicitly flagged in that commit as 'candidates "
                       "for the same treatment later' and then left there across "
                       "several iterations. Wired into all three, each with the "
                       "shape-appropriate predicate: hn/wiki check that at least one "
                       "topic has a non-None recent-window reading; npm (where most "
                       "topics legitimately have no entry at all, package or not) "
                       "checks that the result isn't empty outright, since TOPICS "
                       "always has at least one real npm-eligible entry. Verified "
                       "against real, current data: today's live fetch is fully "
                       "populated for all three (32/32, 31/31, 2 real npm entries) "
                       "and every predicate correctly returns False against it, "
                       "then correctly returns True against a simulated total "
                       "failure of the same shape"},
            {"name": "Simons/Reddington backfill — complete the rollout", "done": True,
             "detail": "the Backfill History commit wired historical_rows() into "
                       "Holmdel and Jackson but explicitly deferred Simons/"
                       "Reddington, reasoning that reconstructing a full scored "
                       "point (z-score, percentile, vol ratio) at an arbitrary past "
                       "date was 'a different, larger shape of work.' Re-examined "
                       "rather than carried forward: analyse() in telescope/"
                       "series.py already treats the *last* point in a series' "
                       "point list as 'now', purely by slicing (values[-1], "
                       "values[-252:], etc.) — so calling it again on the same "
                       "cached points with the final observation dropped "
                       "reconstructs a genuine one-reading-back row with zero new "
                       "math, just a shorter array. New shared helper, "
                       "historical_panel() in telescope/series.py, does exactly "
                       "that by reading each series' already-cached point list "
                       "straight off disk (no network call) and re-running "
                       "analyse() on points[:-1]. Wired into both Simons and "
                       "Reddington in one line each. Verified against real, "
                       "current data: 19/21 Simons series and 12/12 Reddington "
                       "series produced a genuinely different level/z from their "
                       "current reading (e.g. the 10Y Treasury's real close two "
                       "days ago vs today), and clearing real accumulated "
                       "snapshot history and re-sweeping both telescopes from "
                       "scratch produced real first-sweep events (10Y/2Y Treasury "
                       "and VIX climbing on Simons; PPI General Freight LTL "
                       "becoming new leader on Reddington) instead of the usual "
                       "silent-until-the-second-sweep gap"},
            {"name": "Kernel test coverage for telescope/series.py", "done": True,
             "detail": "analyse()/change() (Simons and Reddington's shared "
                       "z-score/percentile/vol-ratio math) and the new "
                       "historical_panel() had zero fast, deterministic tests — "
                       "only ever exercised indirectly by test_live.py's real "
                       "network fetches, which confirms the shape still works but "
                       "can't confirm the arithmetic is right. Before spending this "
                       "iteration, re-checked every other blocked item live rather "
                       "than assume: SAM.gov (404), Semantic Scholar (429), "
                       "Jackson's own SBIR fetch (429 'not available at this "
                       "time'), Reddit's public JSON search (403, locked down "
                       "since 2023) and Google Trends' unofficial endpoint (429 "
                       "immediately) — all still genuinely blocked, no X "
                       "credentials configured either, so nothing on the named "
                       "roadmap was actually actionable this iteration. Added 7 "
                       "synthetic, no-network tests: change()'s two unit branches "
                       "and its not-enough-history case, analyse()'s min_points "
                       "floor and its z-score/percentile/chg_1m math against a "
                       "known monotonic series, and historical_panel()'s slice-"
                       "the-cache reconstruction against a real Cache instance on "
                       "a throwaway tmp dir (both the happy path and the no-"
                       "cache-yet path)"},
            {"name": "Kernel test coverage for telescope/http.py", "done": True,
             "detail": "_request()'s retry/no-retry branching is exactly the kind "
                       "of logic that already caused a real bug once (a plain 404 "
                       "used to fall into the same retry loop as a rate limit, "
                       "wasting ~2.5s of backoff on an expected-common case like a "
                       "guessed job-board slug) and had zero tests pinning the fix "
                       "— a future edit could silently reintroduce it. Re-checked "
                       "every blocked source live again first rather than assume: "
                       "SAM.gov (404), Semantic Scholar (429), SBIR (429 'not "
                       "available at this time') all still blocked, nothing newly "
                       "actionable. Added 6 tests mocking requests.request/"
                       "requests.get directly (what's under test is the "
                       "branching, not any one real API): 429 retries then "
                       "recovers, a plain 404 is not retried at all and sleeps "
                       "zero times (the actual regression test for the bug "
                       "above), 5xx and network exceptions each retry exactly "
                       "RETRIES times before giving up, try_json falls back to "
                       "its default on a permanent failure, and probe_text makes "
                       "exactly one attempt on failure — never retries — since "
                       "its whole purpose is staying cheap across a batch of "
                       "speculative guesses that are mostly wrong"},
            {"name": "Kernel test coverage for telescope/notifier.py", "done": True,
             "detail": "two properties here had zero tests despite being exactly "
                       "the kind of silent-failure-mode logic worth pinning: every "
                       "channel is supposed to no-op (not crash, not POST to an "
                       "empty URL) when its env var isn't configured, and "
                       "dispatch() is supposed to keep plain movers/deltas out of "
                       "social entirely — only SOCIAL_TYPES should ever reach "
                       "Discord/Slack/X. Re-checked the usual blocked sources "
                       "live again first (SAM.gov 404, Semantic Scholar 429, SBIR "
                       "429) — still nothing newly actionable. Added 6 tests "
                       "mocking requests.post and os.environ directly: dispatch() "
                       "correctly filters a non-social event type out before it "
                       "reaches any channel, post_to_discord no-ops without a "
                       "webhook configured and posts when one is, a request "
                       "exception is swallowed rather than propagated, post_to_x "
                       "short-circuits on the credential check before ever "
                       "importing tweepy (an optional dependency that may not "
                       "even be installed), and dispatch_brief always reaches "
                       "stdout regardless of channel configuration"},
            {"name": "Kernel test coverage for telescope/registry.py", "done": True,
             "detail": "the last major untested kernel module — pure logic (an "
                       "enable/disable toggle persisted to JSON) but built on "
                       "module-global state (_classes, _instances, a file on "
                       "disk), which is exactly why it had been skipped in favour "
                       "of series.py/http.py/notifier.py the last three "
                       "iterations: it needs real isolation, not just a mock. "
                       "Re-checked the usual blocked sources live again first "
                       "(SAM.gov 404, Semantic Scholar 429, SBIR 429) — still "
                       "nothing newly actionable. Added a context manager that "
                       "saves and fully restores _classes/_instances/"
                       "_load_errors/STATE_FILE around each test against two "
                       "throwaway fake telescope classes, so nothing here can "
                       "leak into the real registry other tests or the app "
                       "depend on (confirmed: the same pre-existing, unrelated "
                       "OpenAlex live-test failure is the only failure, same as "
                       "every prior iteration). 10 new tests, most pinning the "
                       "one genuinely subtle property in this file: a slug "
                       "registered but never yet saved to disk (a newly-added "
                       "pack on an existing install) must inherit the env-var "
                       "default rather than come up silently enabled just for "
                       "existing — plus register(), both branches of the env-var "
                       "default (all vs. a comma list), set_enabled() not "
                       "clobbering a sibling slug's own persisted state, both "
                       "KeyError paths, get()'s memoisation, and catalog()'s "
                       "shape"},
            {"name": "Live test coverage for historical_rows()", "done": True,
             "detail": "the backfill hook (historical_rows()) is implemented by "
                       "four of six telescopes (Holmdel, Jackson, Simons, "
                       "Reddington) but had only ever been exercised by "
                       "test_kernel.py's hand-built synthetic Telescope stand-"
                       "ins — never against a real telescope's own live collect() "
                       "output, so a crash or malformed row on real data could "
                       "ship unnoticed by either suite. Re-checked OpenAlex's "
                       "status first: still $0 daily budget remaining ('resets "
                       "at midnight UTC', confirmed self-inflicted from this "
                       "session's own repeated test runs, not a new block) and "
                       "the other three usual sources (SAM.gov, Semantic "
                       "Scholar, SBIR) unchanged — nothing newly actionable. New "
                       "generic test in test_live.py, parametrised across all "
                       "six telescopes against today's real data: confirms "
                       "historical_rows() either declines honestly with None "
                       "(Kepler and Hubble's case — nothing resembling a recent "
                       "past to reconstruct) or returns rows that carry key/name "
                       "and survive being run through the exact same rank() "
                       "pipeline a real sweep uses. Passed cleanly against real "
                       "current data for all six on the first run"},
            {"name": "Cache resilience for telescope/series.py's fetch_panel()",
             "done": True,
             "detail": "Simons and Reddington's primary signal (every scored row "
                       "on both boards comes through here) had the exact same "
                       "cache-poisoning exposure that once briefly zeroed "
                       "Holmdel's OpenAlex signal for half a day, just never "
                       "found until checking every cache.cached() call across "
                       "the fleet: a transient FRED/Yahoo/CoinGecko outage would "
                       "write an empty points list to that series' cache file "
                       "and get served as truth for the rest of ttl (up to 6h "
                       "for Reddington's monthly-cadence gauges), silently "
                       "dropping a series that was fine moments ago. Simpler "
                       "than Holmdel's per-source predicates: each series here "
                       "has its own cache key (unlike Holmdel's per-topic "
                       "sources, which share one file across all 32 topics and "
                       "need an aggregate check), and every declared Series is "
                       "an established, actively-tracked indicator expected to "
                       "always have history once ever fetched — so 'this fetch "
                       "came back empty' is already the correctly-scoped "
                       "per-series failure signal, one line: "
                       "is_empty=lambda r: not r. Verified against real, current "
                       "data: today's live fetch for a real Simons series (the "
                       "10Y Treasury, 16,134 real cached points) is untouched by "
                       "the predicate, then simulating a total outage on that "
                       "exact series confirmed the real stale history is served "
                       "instead of being overwritten with []. Also checked "
                       "Jackson's and Kepler's own cache.cached() calls for the "
                       "same gap while here — both still lack it, flagged below "
                       "as separate follow-up work rather than folded in, since "
                       "each needs its own shape-appropriate predicate the way "
                       "Holmdel's five sources each did"},
            {"name": "Cache resilience for Jackson's and Kepler's own sources",
             "done": True,
             "detail": "found while fixing the same gap in telescope/series.py: "
                       "Jackson's _category()/_award_counts() called post_json() "
                       "directly with no fallback at all — unlike every other "
                       "fetcher in the fleet (built on try_json/try_text, which "
                       "degrade to a default), a single USAspending hiccup would "
                       "crash the whole collect() rather than just return what "
                       "had already succeeded. Fixed with a narrow try/except "
                       "around the paginating call (SourceError, ValueError — "
                       "matching try_json's own catch tuple, since a malformed "
                       "non-JSON body isn't a SourceError either), returning "
                       "whatever pages already succeeded instead of crashing. "
                       "Then added is_empty to recipients_12m/recipients_prior/"
                       "award_counts/psc/psc_prior: DoD obligations, awards and "
                       "PSC spend are never genuinely zero in a real 12-month "
                       "window, so an empty result is unambiguously a fetch "
                       "failure. For Kepler, audited all five sources rather "
                       "than assume the same fix applies uniformly — most "
                       "already degrade gracefully per-item and legitimately "
                       "return near-empty results under full health (12/220 "
                       "issuers resolve a domain in a normal sweep, 1/40 match "
                       "a hiring board), so forcing is_empty there would wrongly "
                       "treat a correct 'found nothing this time' as a failure "
                       "and freeze on stale data forever — the exact trap "
                       "Holmdel's own npm predicate had to design around. Only "
                       "wired the two sources where empty is unambiguous: "
                       "_filings() (every business day has real Form D activity; "
                       "_index_day() already isolates a single bad day, so only "
                       "a total outage across the whole lookback window empties "
                       "it) and _hn() (an entry is recorded for every name that "
                       "gets a successful response, zero hits included — only a "
                       "raised exception skips one, so empty means every lookup "
                       "failed). Left _domains()/_hiring()/_details() alone; "
                       "their sparse-by-design output makes 'empty' ambiguous. "
                       "Verified against real, current data for both telescopes: "
                       "confirmed today's live fetches (100 Jackson recipients, "
                       "118 award counts, 25/60 PSC entries, 453 Kepler filings, "
                       "35 HN entries) all pass the predicates untouched, then "
                       "simulated a total outage on each exact cache key and "
                       "confirmed the real data survives instead of being "
                       "overwritten"},
            {"name": "Poller retries a failed sweep on the next tick, not next cycle",
             "done": True,
             "detail": "found while thinking through what the last two "
                       "iterations' cache-resilience fixes actually protect "
                       "against: even with is_empty guarding every cache write, "
                       "a genuine fetch failure still needs a *retry*, and "
                       "app.py's poller was treating a failed sweep exactly "
                       "like a successful one for scheduling purposes — "
                       "safe_sweep() returning [] on either an exception or a "
                       "real 'nothing changed' sweep, with the poller "
                       "unconditionally advancing last[slug] either way. A "
                       "transient failure on a 24h-cadence telescope like "
                       "Jackson would silently not retry for a full day. "
                       "Two-part fix: safe_sweep() now clears _last_error on a "
                       "successful attempt (it previously only ever set it on "
                       "failure, so a telescope that recovered would keep "
                       "reporting a stale error via meta() forever — nothing "
                       "else on that path ever reset it); the poller now only "
                       "advances last[slug] when _last_error is None after the "
                       "call, so a real failure retries on the very next 60s "
                       "tick instead of waiting a full poll_seconds. Verified "
                       "against a real, live-registered Jackson instance, not "
                       "synthetic: a genuine successful sweep advances the "
                       "schedule, injecting a real exception into collect() "
                       "leaves it unadvanced with the actual error message "
                       "recorded, and restoring the real collect() and "
                       "sweeping again both clears the error and resumes "
                       "advancing. Added 2 kernel tests pinning safe_sweep()'s "
                       "error-tracking directly"},
            {"name": "Cache resilience for Hubble's own sources", "done": True,
             "detail": "the cache-resilience audit had covered Simons/"
                       "Reddington, Jackson and Kepler but never circled back to "
                       "Hubble itself — the original, reference telescope — "
                       "which turned out to have the exact same bug fixed in "
                       "Jackson two iterations ago: fetch_huggingface() and "
                       "fetch_openrouter() called get_json() directly with no "
                       "fallback at all, so a transient HuggingFace or "
                       "OpenRouter outage would crash the whole sweep instead "
                       "of degrading like every other fetcher in the fleet. "
                       "Unlike Jackson's case this was a one-line fix per "
                       "fetcher rather than a new try/except block — both are "
                       "plain GET calls, so try_json (already built for "
                       "exactly this) was a straight swap-in, no new kernel "
                       "code needed. Then added is_empty to both: "
                       "HuggingFace's text-generation models sorted by "
                       "downloads and OpenRouter's weekly usage ranking are "
                       "never legitimately empty, so an empty result is "
                       "unambiguously a fetch failure. Left fetch_lmarena() "
                       "alone — its own docstring already says 'best effort; "
                       "may be empty,' the same category as Kepler's "
                       "_domains()/_hiring(), where forcing is_empty would "
                       "treat a correct empty reading as a failure. Verified "
                       "against real, current data: today's live fetch (300 "
                       "HuggingFace models, 400 OpenRouter models) is untouched "
                       "by the predicates, and simulating a total outage on "
                       "both confirmed the real cached data survives instead "
                       "of being overwritten. This closes out the "
                       "cache-resilience audit across all six telescopes"},
            {"name": "Cache resilience for Simons' WHALE MOVES panel", "done": True,
             "detail": "the prior iteration's 'closes out the audit across all "
                       "six telescopes' claim was premature — it covered "
                       "Simons' primary series via telescope/series.py's "
                       "fetch_panel(), but not the separate WHALE MOVES "
                       "secondary panel's own 13F fetchers (_accessions(), "
                       "_positions()), a genuinely different code path. Found "
                       "the highest-confidence case in this whole audit: "
                       "_positions()' cache (one specific filing's holdings) "
                       "uses a 90-day TTL specifically *because* a filing's "
                       "content is immutable once filed — but that same "
                       "permanence meant a transient SEC outage returning {} "
                       "would poison that one filing's cache for the full 90 "
                       "days, not just until the next sweep, silently blanking "
                       "a whale's WHALE MOVES entry for a whole quarter. A real "
                       "13F-HR from a manager large enough to be on the "
                       "curated WHALES list always reports some positions, so "
                       "empty is unambiguous. Same reasoning for _accessions(): "
                       "every curated whale always has at least two historical "
                       "13F-HR filings. Verified against real, current data: "
                       "today's cached accessions and a real filing's 29 "
                       "positions for the first whale on the list both pass "
                       "the predicates untouched, and simulating a total "
                       "outage on both confirmed the real data survives "
                       "instead of being overwritten"},
            {"name": "Brief scheduler retries a failed build on the next tick",
             "done": True,
             "detail": "the exact same bug the poller had, in the other "
                       "background thread in app.py: _brief_scheduler() "
                       "advanced its own retry clock (`last = time.time()`) "
                       "unconditionally after its try/except, so a single "
                       "failed digest build or dispatch (any telescope's "
                       "cached board being briefly unreadable, a notifier "
                       "hiccup) would silently not retry for a full "
                       "BRIEF_HOURS — 24h by default — instead of the very "
                       "next 60s tick. Found by checking whether the poller "
                       "fix from two iterations ago had a sibling anywhere "
                       "else in app.py, rather than assume it was the only "
                       "background loop with this shape. Same fix: only "
                       "advance `last` inside the try block, after a genuine "
                       "success, not unconditionally after it. Verified "
                       "against real, current data rather than synthetic: ran "
                       "the exact fixed decision logic against the real "
                       "telescope.brief.build()/notifier.dispatch_brief() path "
                       "twice — once for real (produced and logged a genuine "
                       "digest, including a real live Hubble climber event) "
                       "confirming the schedule advances, then with a real "
                       "exception injected into build() confirming the "
                       "schedule does not advance and will retry next tick"},
            {"name": "Test coverage for app.py's Flask API layer", "done": True,
             "detail": "app.py's own routes — /api/telescope/<slug>, /api/"
                       "observatory, the merged feed, the brief endpoints, the "
                       "toggle endpoint — had zero coverage in either suite "
                       "despite being the actual surface the frontend and any "
                       "API consumer talk to. Every prior test exercised "
                       "telescope logic directly, never through the HTTP layer "
                       "itself, so a route registration typo, a JSON "
                       "serialization bug, or a wrong status code could ship "
                       "unnoticed. Found by checking whether the poller/brief-"
                       "scheduler fixes had left any adjacent surface in "
                       "app.py unaudited, the same question that turned up the "
                       "brief-scheduler bug last iteration. Added 13 tests to "
                       "test_live.py (kept to two suites rather than adding a "
                       "third, since Flask's test_client() against the real "
                       "registered telescopes fits that file's actual scope) "
                       "using force=False throughout, so every GET reads "
                       "already-cached data rather than fetching — no new "
                       "network calls beyond what the rest of the suite "
                       "already warms. Covers a wellformed payload for all six "
                       "telescopes' main endpoint, the observatory listing, "
                       "roadmap, per-telescope and merged event feeds, the "
                       "brief endpoint, and both 404 paths (unknown telescope, "
                       "unknown toggle target) without ever writing to the "
                       "same data/observatory.json the real dev server reads. "
                       "All 13 passed against real, current data on the first "
                       "run"},
            {"name": "Flask dev server handles requests concurrently", "done": True,
             "detail": "found by actually using the live dashboard rather than "
                       "only its API: switching to Simons and saving a "
                       "weighting view worked, but the UI appeared to freeze "
                       "on a subsequent interaction while Kepler was mid-"
                       "refresh. app.run() had no threaded=True, which is "
                       "Werkzeug's well-documented default — the dev server "
                       "handles one request at a time. Every collect() call "
                       "is I/O-bound (network + time.sleep pacing) and "
                       "releases the GIL, so a single slow fetch — Kepler's "
                       "per-issuer paced lookups, a Holmdel sweep hitting "
                       "arXiv's throttle — was blocking every other request "
                       "behind it, including completely unrelated ones like "
                       "loading the observatory catalog or switching to an "
                       "already-cached telescope. One-line fix: "
                       "app.run(..., threaded=True). Verified conclusively "
                       "against the fix, not just the symptom: fired a "
                       "guaranteed-slow forced Kepler refresh "
                       "(?refresh=1) and, two seconds later while it was "
                       "still running, hit a completely unrelated endpoint "
                       "concurrently — it returned in 0.0017s instead of "
                       "queuing behind the still-in-flight 300+ second "
                       "request, exactly the behavior threaded=True is "
                       "supposed to produce. Also did a fresh UI pass while "
                       "here: confirmed the watchlist (star, persist across a "
                       "real reload, WATCHED ONLY filter, scope isolation) "
                       "and saved views (save, apply restores exact weights, "
                       "delete, scope isolation) both still work correctly "
                       "after all the backend churn this session — no other "
                       "regressions found"},
            {"name": "Brief tab no longer hangs on a stale telescope cache",
             "done": True,
             "detail": "found immediately after fixing the Flask threading "
                       "issue, while continuing the same 'actually click "
                       "through the dashboard' verification pass: the BRIEF "
                       "tab itself hung for minutes. telescope/brief.py's own "
                       "docstring claims build() 'never forc[es] a fresh "
                       "sweep, so building a brief is always cheap regardless "
                       "of how expensive an individual telescope's own "
                       "collect() is' — but it called "
                       "scope.rank(scope.collect(force=False)), and "
                       "force=False is not the same as cheap: if a "
                       "telescope's cache has simply expired via its own "
                       "TTL, force=False still triggers a real, potentially "
                       "slow, paced live fetch, exactly what a real sweep "
                       "would do. Confirmed directly, outside Flask entirely: "
                       "brief.build() took over two minutes in a fresh "
                       "Python process with a stale Kepler cache, flatly "
                       "contradicting its own contract. No existing test ever "
                       "caught this because every prior test ran right after "
                       "the whole fleet's cache had just been warmed by the "
                       "rest of that same test session. Fixed by reading "
                       "scope.store.latest() instead — a snapshot already on "
                       "disk from the last real sweep, a pure disk read with "
                       "no network involved at all, genuinely matching the "
                       "'always cheap' contract rather than just claiming "
                       "it. Verified against real, current data: build() now "
                       "takes 0.0054s (was 120s+) and produces the exact "
                       "same real leaders across all six telescopes as "
                       "before (confirmed against the dev server's own "
                       "recently-logged brief output); the live BRIEF tab "
                       "itself now loads in 14ms. Added a kernel regression "
                       "test asserting collect() is never called during "
                       "build()"},
            {"name": "Cross-telescope joins actually never force a sweep",
             "done": True,
             "detail": "the exact same bug just found in telescope/brief.py's "
                       "build() — collect(force=False) looks like it honours "
                       "a 'never forces a refresh' promise but doesn't, since "
                       "a telescope's own cache simply expiring via its own "
                       "TTL still triggers a real, slow, paced live fetch — "
                       "turned out to have two more live instances, both in "
                       "cross-telescope joins whose own docstrings explicitly "
                       "promise the opposite: Jackson's UNMAPPED panel called "
                       "get_telescope('kepler').collect(force=False) despite "
                       "its docstring saying 'never forces a refresh... "
                       "forcing it from here would mean loading Jackson "
                       "silently triggers a slow SEC EDGAR sweep' — the exact "
                       "failure it was trying to describe avoiding, but "
                       "didn't. Kepler's SECTOR HEAT panel had the identical "
                       "shape reading Holmdel, whose own arXiv/GitHub-paced "
                       "sources are the slowest in the fleet. Found by "
                       "grepping for every other collect(force=False)/"
                       "collect() call in the codebase after fixing brief.py, "
                       "rather than assume it was the only instance. Fixed "
                       "both the same way: read store.latest() instead — a "
                       "pure disk read of the OTHER telescope's last real "
                       "sweep, genuinely incapable of forcing one. Confirmed "
                       "both panels' needed fields (industry/raise_size for "
                       "Kepler, group for Holmdel) are already declared in "
                       "each telescope's own snapshot_fields before making "
                       "the change. Left the third occurrence, Kepler's own "
                       "self.collect(force=False) inside its SECTOR HEAT "
                       "panel, unchanged — that one reads its *own* just-"
                       "collected data within the same view() call, not a "
                       "different telescope's independently-aged cache, so "
                       "it correctly hits the fresh cache from moments "
                       "earlier in the same request rather than forcing "
                       "anything. Verified against real, current data: "
                       "Jackson's UNMAPPED panel and Kepler's "
                       "_crossed_over_groups()/_sector_heat_panel() each now "
                       "run in under 4 milliseconds (previously capable of "
                       "the same multi-minute hang brief.py had) and produce "
                       "the same real results as before — Kepler's crossover "
                       "groups still correctly include World Models, AI "
                       "Agents, Local Inference and Mechanistic "
                       "Interpretability, all real events already visible in "
                       "the dev server's own logs"},
            {"name": "Fixed a stale-response race condition when switching telescopes",
             "done": True,
             "detail": "found doing a full pass over every remaining untested "
                       "UI mechanism (search, column sort, HIDE NOISE/SCORED "
                       "ONLY, watchlist, saved views, toggles, tooltip, "
                       "REFRESH) after the last two iterations' cross-"
                       "telescope-join fixes — the REFRESH button check "
                       "surfaced a real, cleanly reproducible bug. load() in "
                       "static/app.js reads state.slug into its request URL, "
                       "awaits the fetch, then unconditionally applies "
                       "whatever comes back. With no request sequencing, "
                       "clicking REFRESH on one telescope (forces a live "
                       "fetch, can take minutes on a cold cache) and then "
                       "switching to a different, already-cached telescope "
                       "starts a second, independent load() — and whichever "
                       "fetch happens to resolve last wins, regardless of "
                       "which one reflects the user's actual most recent "
                       "action. Reproduced cleanly: refresh Jackson, switch "
                       "to Simons three-tenths of a second later, wait for "
                       "both to finish — the board reverted to showing "
                       "Jackson's stale refreshed data instead of Simons, "
                       "which is what the user actually asked to see last. "
                       "Fixed with a staleness guard: load() now captures "
                       "the slug it was called for and discards its own "
                       "result (skips every state mutation and re-render) if "
                       "state.slug no longer matches by the time the fetch "
                       "resolves — a switch that happened while the request "
                       "was in flight already reflects what the user wants "
                       "to see. Verified against the exact reproduction "
                       "above, live: after the fix, waiting for both "
                       "requests to fully resolve leaves the board correctly "
                       "showing Simons (21 real rows), not Jackson. No "
                       "automated regression test added — this file has no "
                       "JS test framework, matching how every other "
                       "frontend-only fix this session was verified live "
                       "rather than via an automated test"},
            {"name": "Kepler domains cache resilience via a canary probe",
             "done": True,
             "detail": "closes a gap explicitly left open when Jackson's and "
                       "Kepler's other sources got is_empty guards: "
                       "_domains() couldn't get the same blanket treatment "
                       "because it's genuinely, legitimately near-empty most "
                       "sweeps (12/220 issuers resolve a domain on a normal "
                       "day) — forcing is_empty there would misread a correct "
                       "'40 guesses missed' as a failure and freeze on stale "
                       "data forever. The blocker was real but solvable: "
                       "probe_text folds every failure mode (dead DNS, "
                       "timeout, non-200) into the same None, so there was no "
                       "way to tell 'the guesses were wrong' from 'our own "
                       "network is down' from the result alone. Fixed with a "
                       "canary: only when the sweep comes back empty, probe "
                       "a domain that's always up (google.com) — if that "
                       "also fails, it's a real outage worth falling back to "
                       "stale data for; if it succeeds, an empty result "
                       "really is just 40 wrong guesses, the expected common "
                       "case, and should be cached as-is. Verified against "
                       "real, current data in both directions: today's real "
                       "sweep found the expected 12/220 real domains and "
                       "correctly never invokes the canary at all (only "
                       "checked when the result is empty); directly testing "
                       "the predicate with the real network up confirmed an "
                       "empty result reads as 'not a failure', and a "
                       "simulated total outage (probe_text mocked to always "
                       "fail) correctly flipped it to 'is a failure'. Also "
                       "re-checked Semantic Scholar, which returned a "
                       "genuine 200 once this iteration for the first time "
                       "all session — confirmed a fluke, not a real "
                       "unblocking, by retrying four more times immediately "
                       "after: back to 429 every time, consistent with its "
                       "documented tiny globally-shared unauthenticated "
                       "quota rather than a persistent block that's lifted"},
            {"name": "Kepler hiring cache resilience via the same canary probe",
             "done": True,
             "detail": "the direct follow-up flagged when _domains() got its "
                       "canary fix: _hiring() has the exact same shape — a "
                       "documented 1/40 real hit rate across Greenhouse/"
                       "Lever/Ashby, so an empty result is the expected "
                       "common case, not a failure, and try_json folds a "
                       "dead guess and a genuine outage into the same None "
                       "with no way to tell them apart from the result "
                       "alone. Same fix, same reasoning: probe google.com "
                       "only when the sweep comes back empty. Verified "
                       "against real, current data: today's live sweep found "
                       "exactly 1/40 matches (MedRhythms, Inc. -> Lever, 8 "
                       "open roles — the same real company this exact signal "
                       "was verified against when it first shipped), so the "
                       "canary correctly never fires; directly testing the "
                       "predicate confirmed all three cases (non-empty, "
                       "empty-with-real-network, empty-with-simulated-outage) "
                       "resolve correctly, and simulating a total failure "
                       "through the real cache confirmed the real MedRhythms "
                       "entry survives instead of being overwritten with {}. "
                       "Re-checked the usual blocked sources again: SAM.gov "
                       "(404), Semantic Scholar (429, the single 200 from "
                       "last iteration was confirmed a fluke), SBIR (429) — "
                       "all unchanged"},
            {"name": "Kepler details cache resilience — the last of the five",
             "done": True,
             "detail": "closes out the audit of Kepler's own five sources "
                       "(filings, hn, hiring, domains now all done; details "
                       "was the last). Deliberately NOT the same canary fix "
                       "as domains/hiring — that would have been wrong here. "
                       "_detail()'s only exception path is get_text() itself "
                       "raising on a real fetch failure: _tag()/_num() are a "
                       "regex search and a try/except float(), neither can "
                       "ever raise, so every filing whose primary_doc.xml is "
                       "actually reachable adds a real entry to the result "
                       "regardless of how sparse its individual fields turn "
                       "out to be. An aggregate-empty result therefore means "
                       "every single fetch in the batch failed at the "
                       "network level — a real outage, not 'no economics "
                       "data found' the way an empty domains/hiring result "
                       "usually is — so the plain is_empty=lambda r: not r "
                       "already used for filings()/_hn() is the correct, "
                       "sufficient fix here, no canary needed. Verified "
                       "against real, current data: today's live sweep got "
                       "real economics data for all 220/220 filings "
                       "attempted, and simulating a total outage through the "
                       "real cache confirmed all 220 real entries survive "
                       "instead of being overwritten with {}"},
            {"name": "Test coverage for the /sweep API route", "done": True,
             "detail": "the last untested app.py route — every earlier Flask "
                       "API test used force=False (reads whatever's already "
                       "cached), so /api/telescope/<slug>/sweep, the one "
                       "route that forces a real collect(force=True) and "
                       "writes a real snapshot, was never exercised through "
                       "the HTTP layer. Timed a real forced Reddington sweep "
                       "first (5.78s) before deciding whether adding it was "
                       "worth the extra suite time — Reddington's small (12 "
                       "gauges), unpaced fetch_panel() keeps this fast, "
                       "unlike Kepler/Holmdel which can take minutes on a "
                       "cold cache; that slow-path behavior is already "
                       "covered by this session's threading and staleness-"
                       "guard work. Also re-checked Semantic Scholar, which "
                       "returned a genuine 200 again this iteration — "
                       "re-confirmed still fundamentally unusable by hitting "
                       "it 8 more times with 3s spacing: 429 every single "
                       "time, the same isolated-fluke pattern as before, not "
                       "a real unblocking"},
            {"name": "Removed Hubble's permanently-dead LMArena fallback",
             "done": True,
             "detail": "found while re-examining Hubble's fetch_lmarena() "
                       "with the same rigor recently applied to Kepler's "
                       "sources — its is_empty status had been left as "
                       "'best effort; may be empty' without ever actually "
                       "re-verifying that reasoning against a real current "
                       "fetch. It doesn't hold: the real fetch returns a "
                       "genuine 404 — the leaderboard.csv file no longer "
                       "exists at that path in lm-sys/FastChat at all, "
                       "confirmed by listing the repo's monitor/ directory "
                       "directly, not just the one guessed URL. This fetcher "
                       "has been silently contributing zero real signal for "
                       "the entire session (and likely far longer), with no "
                       "error ever surfaced, because it's a supplementary "
                       "fallback: arena_elo tries OpenRouter's own embedded "
                       "Design Arena data first, and the dead LMArena source "
                       "was only ever meant to fill gaps for models missing "
                       "there. Investigated whether a live replacement "
                       "exists before deciding what to do: LMArena has since "
                       "become its own product at a dedicated domain, whose "
                       "frontend is a JS app with its guessed /api/ path "
                       "blocked (403, not something to try bypassing); the "
                       "closest thing to a structured data file is a "
                       "community-maintained mirror on Hugging Face Spaces, "
                       "but its most recent file is roughly a year stale — "
                       "silently serving that as 'live' arena data would be "
                       "worse than having none, presenting outdated rankings "
                       "as current. Removed the dead fetcher entirely rather "
                       "than leave it silently doing nothing: arena_elo now "
                       "comes from OpenRouter's own data only, and the "
                       "caveat states this plainly. Verified against real, "
                       "current data: today's live fetch still populates "
                       "arena_elo for 144/650 real models from OpenRouter's "
                       "own Design Arena data, unchanged from before removal "
                       "since the dead fallback was already contributing "
                       "nothing"},
        ],
    },
]


def as_markdown():
    """Render the same data as Markdown for ROADMAP.md."""
    out = ["# 🔭 Observatory — feature roadmap", ""]
    out.append("_Generated from `roadmap.py`, which also backs the dashboard's "
               "ROADMAP tab._")
    out.append("")
    for p in PHASES:
        done = sum(1 for i in p["items"] if i["done"])
        out.append(f"## {p['title']}  ·  `{p['status']}`  ({done}/{len(p['items'])})")
        out.append("")
        if p.get("note"):
            out.append(f"> {p['note']}")
            out.append("")
        for i in p["items"]:
            box = "x" if i["done"] else " "
            detail = f" — {i['detail']}" if i.get("detail") else ""
            out.append(f"- [{box}] **{i['name']}**{detail}")
        out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    print(as_markdown())
